name: sub_state
description: A lightweight state management helper built on top of bloc and freezed.
version: 0.0.3
homepage: https://github.com/mohamadalghanem474/sub_state
repository: https://github.com/mohamadalghanem474/sub_state
issue_tracker: https://github.com/mohamadalghanem474/sub_state/issues
documentation: https://github.com/mohamadalghanem474/sub_state#readme

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3

flutter: null

# No assets or fonts yet, but leave section ready
