name: sub_state
description: A lightweight state management helper.
homepage: https://github.com/mohamadalghanem474/sub_state
repository: https://github.com/mohamadalghanem474/sub_state
issue_tracker: https://github.com/mohamadalghanem474/sub_state/issues
documentation: https://github.com/mohamadalghanem474/sub_state#readme
version: 1.0.7

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^5.0.0
  freezed: ^3.2.3

screenshots:
  - description: The sub_state package logo.
    path: screenshots/logo.png

